// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addSelectedButton': string;
  'buttonContainer': string;
  'buttonContainerContent': string;
  'buttons': string;
  'excludeSelectedButton': string;
  'inputContainer': string;
  'selectedMovieLabel': string;
}
export const cssExports: CssExports;
export default cssExports;
