// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'divider': string;
  'hintText': string;
  'isMobile': string;
  'optionText': string;
}
export const cssExports: CssExports;
export default cssExports;
