// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'buttonWrapper': string;
  'inputWrapper': string;
  'itemContainer': string;
  'keyInput': string;
  'valueInput': string;
}
export const cssExports: CssExports;
export default cssExports;
