// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'input': string;
  'internalInput': string;
  'isFocused': string;
}
export const cssExports: CssExports;
export default cssExports;
