// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'alert': string;
  'filterMenuContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
