// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'age': string;
  'blocklist': string;
  'cell': string;
  'customFormat': string;
  'customFormatScore': string;
  'download': string;
  'history': string;
  'indexer': string;
  'indexerFlags': string;
  'language': string;
  'peers': string;
  'protocol': string;
  'quality': string;
  'rejected': string;
  'size': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
