// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'indexer': string;
  'language': string;
  'quality': string;
}
export const cssExports: CssExports;
export default cssExports;
