// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'progress': string;
  'progressBar': string;
  'progressRadius': string;
}
export const cssExports: CssExports;
export default cssExports;
