// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'detailsIcon': string;
  'folder': string;
  'minimumAvailability': string;
  'monitor': string;
  'movie': string;
  'qualityProfile': string;
}
export const cssExports: CssExports;
export default cssExports;
