// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'path': string;
  'previews': string;
  'selectAllInput': string;
  'selectAllInputContainer': string;
  'standardMovieFormat': string;
}
export const cssExports: CssExports;
export default cssExports;
