// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'age': string;
  'customFormatScore': string;
  'download': string;
  'formats': string;
  'language': string;
  'quality': string;
  'rejected': string;
  'relativePath': string;
  'releaseGroup': string;
  'size': string;
}
export const cssExports: CssExports;
export default cssExports;
