name: Bug Report
description: 'Report a new bug, if you are not 100% certain this is a bug please go to our Discord first'
labels: ['Type: Bug', 'Status: Needs Triage']
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an open or closed issue already exists for the bug you encountered. If a bug exists and is closed note that it may only be fixed in an unstable branch. 
    options:
    - label: I have searched the existing open and closed issues
      required: true
- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. In this environment...
      2. With this config...
      3. Run '...'
      4. See error...
  validations:
    required: false
- type: textarea
  attributes:
    label: Environment
    description: |
      examples:
        - **OS**: Ubuntu 20.04
        - **Radarr**: Radarr 3.0.1.4259
        - **Docker Install**: Yes
        - **Using Reverse Proxy**: No
        - **Browser**: Firefox 90 (If UI related)
        - **Database**: Sqlite 3.36.0
    value: |
        - OS: 
        - Radarr: 
        - Docker Install: 
        - Using Reverse Proxy: 
        - Browser: 
        - Database: 
    render: markdown
  validations:
    required: true
- type: dropdown
  attributes:
    label: What branch are you running?
    options:
      - Master
      - Develop
      - Nightly
      - Other (This issue will be closed)
  validations:
    required: true
- type: textarea
  attributes:
    label: Trace Logs? **Not Optional**
    description: |
      Trace Logs (https://wiki.servarr.com/radarr/troubleshooting#logging-and-log-files) 
      ***Generally speaking, all bug reports MUST have trace logs provided.***
      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
      Additionally, any additional info? Screenshots? References? Anything that will give us more context about the issue you are encountering!
  validations:
    required: true
- type: checkboxes
  attributes:
    label: Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.
    description: Trace logs are **generally required** and are not optional for all bug reports and contain `trace`. Info logs are invalid for bug reports and do not contain `debug` nor `trace`
    options:
    - label: I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.
      required: true
