// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'clearLookupButton': string;
  'helpText': string;
  'message': string;
  'noMoviesText': string;
  'noResults': string;
  'searchContainer': string;
  'searchIconContainer': string;
  'searchInput': string;
  'searchResults': string;
}
export const cssExports: CssExports;
export default cssExports;
