// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addButton': string;
  'container': string;
  'info': string;
  'labelIcon': string;
  'modalFooter': string;
  'overview': string;
  'poster': string;
  'searchForMissingMovieContainer': string;
  'searchForMissingMovieInput': string;
  'searchForMissingMovieLabel': string;
  'searchForMissingMovieLabelContainer': string;
  'year': string;
}
export const cssExports: CssExports;
export default cssExports;
