// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'alreadyExistsIcon': string;
  'certification': string;
  'content': string;
  'exclusionIcon': string;
  'genres': string;
  'icons': string;
  'links': string;
  'originalLanguage': string;
  'overlay': string;
  'overview': string;
  'poster': string;
  'posterContainer': string;
  'runtime': string;
  'searchResult': string;
  'statusContainer': string;
  'studio': string;
  'title': string;
  'titleContainer': string;
  'titleRow': string;
  'underlay': string;
  'year': string;
}
export const cssExports: CssExports;
export default cssExports;
