// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'content': string;
  'details': string;
  'editorSelect': string;
  'ended': string;
  'externalLinks': string;
  'info': string;
  'link': string;
  'overview': string;
  'poster': string;
  'posterContainer': string;
  'queue': string;
  'title': string;
  'titleRow': string;
}
export const cssExports: CssExports;
export default cssExports;
