// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  dashboard: string;
  mediaCard: string;
  mediaCardHeader: string;
  mediaCardTitle: string;
  statsGrid: string;
  statsLabel: string;
  statsRow: string;
  statsValue: string;
  totalCard: string;
  totalCardTitle: string;
  totalValue: string;
}
export const cssExports: CssExports;
export default cssExports;
