// This file is automatically generated.
export default interface CssExports { 'grid': string; 'stats': string; 'toolbar': string; 'visibility': string; 'widget': string; 'widgetBody': string; 'widgetControls': string; }
