// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'monitorToggleButton': string;
  'titleLink': string;
}
export const cssExports: CssExports;
export default cssExports;
