// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'healthOk': string;
  'legend': string;
  'loading': string;
  'status': string;
}
export const cssExports: CssExports;
export default cssExports;
