// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'footerButtons': string;
  'importListExclusionsHeader': string;
  'movieYear': string;
  'title': string;
  'tmdbId': string;
}
export const cssExports: CssExports;
export default cssExports;
