// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'movie': string;
  'tmdbLink': string;
  'tmdbLinkIcon': string;
}
export const cssExports: CssExports;
export default cssExports;
