// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addRestriction': string;
  'center': string;
  'restrictions': string;
}
export const cssExports: CssExports;
export default cssExports;
