// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'freeSpace': string;
  'isMissing': string;
  'isMobile': string;
  'movieFolder': string;
  'optionText': string;
  'value': string;
}
export const cssExports: CssExports;
export default cssExports;
