// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'freeSpace': string;
  'movieFolder': string;
  'path': string;
  'pathContainer': string;
  'selectedValue': string;
}
export const cssExports: CssExports;
export default cssExports;
