// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'certification': string;
  'collection': string;
  'digitalRelease': string;
  'genres': string;
  'imdbRating': string;
  'inCinemas': string;
  'isPopular': string;
  'isRecommendation': string;
  'isTrending': string;
  'lists': string;
  'originalLanguage': string;
  'physicalRelease': string;
  'popularity': string;
  'rottenTomatoesRating': string;
  'runtime': string;
  'sortTitle': string;
  'status': string;
  'studio': string;
  'tmdbRating': string;
}
export const cssExports: CssExports;
export default cssExports;
