// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'alreadyExistsIcon': string;
  'cell': string;
  'certification': string;
  'checkInput': string;
  'collection': string;
  'digitalRelease': string;
  'exclusionIcon': string;
  'externalLinks': string;
  'genres': string;
  'inCinemas': string;
  'isRecommendation': string;
  'lists': string;
  'originalLanguage': string;
  'physicalRelease': string;
  'ratings': string;
  'runtime': string;
  'sortTitle': string;
  'status': string;
  'studio': string;
}
export const cssExports: CssExports;
export default cssExports;
