// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'continuing': string;
  'downloaded': string;
  'event': string;
  'genres': string;
  'info': string;
  'missingMonitored': string;
  'missingUnmonitored': string;
  'movieInfo': string;
  'movieTitle': string;
  'overlay': string;
  'queue': string;
  'statusContainer': string;
  'statusIcon': string;
  'underlay': string;
  'unmonitored': string;
}
export const cssExports: CssExports;
export default cssExports;
