// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'continuing': string;
  'downloaded': string;
  'legendItem': string;
  'missingMonitored': string;
  'missingUnmonitored': string;
  'queue': string;
  'unmonitored': string;
}
export const cssExports: CssExports;
export default cssExports;
