// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'action': string;
  'container': string;
  'content': string;
  'controls': string;
  'editorSelect': string;
  'externalLinks': string;
  'link': string;
  'monitorToggleButton': string;
  'overlay': string;
  'overlayTitle': string;
  'poster': string;
  'posterContainer': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
