// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'danger': string;
  'info': string;
  'movie': string;
  'movieStatus': string;
  'movieTitle': string;
  'primary': string;
  'purple': string;
  'queue': string;
  'success': string;
  'warning': string;
}
export const cssExports: CssExports;
export default cssExports;
