// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'content': string;
  'defaults': string;
  'details': string;
  'detailsLabel': string;
  'editorSelect': string;
  'genres': string;
  'info': string;
  'labelsContainer': string;
  'monitorToggleButton': string;
  'movie': string;
  'moviesContainer': string;
  'navigationButtons': string;
  'overview': string;
  'path': string;
  'qualityProfileName': string;
  'sliderContainer': string;
  'status': string;
  'title': string;
  'titleContainer': string;
  'titleRow': string;
  'toggleMonitoredContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
