// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  clearLookupButton: string;
  helpText: string;
  message: string;
  noAudiobooksText: string;
  noResults: string;
  searchContainer: string;
  searchIconContainer: string;
  searchInput: string;
  searchResult: string;
  searchResults: string;
  subtitle: string;
  title: string;
}
export const cssExports: CssExports;
export default cssExports;
