// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'action': string;
  'container': string;
  'content': string;
  'controls': string;
  'externalLinkLabel': string;
  'externalLinks': string;
  'monitorToggleButton': string;
  'overlayTitle': string;
  'poster': string;
  'posterContainer': string;
  'title': string;
  'toggleMonitoredContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
