// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  container: string;
  description: string;
  detailRow: string;
  details: string;
  header: string;
  label: string;
  monitoredIcon: string;
  title: string;
  value: string;
}
export const cssExports: CssExports;
export default cssExports;
