// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'alreadyExistsIcon': string;
  'content': string;
  'details': string;
  'editorSelect': string;
  'exclusionIcon': string;
  'info': string;
  'link': string;
  'lists': string;
  'overview': string;
  'poster': string;
  'posterContainer': string;
  'title': string;
  'titleRow': string;
}
export const cssExports: CssExports;
export default cssExports;
