// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'action': string;
  'badges': string;
  'container': string;
  'content': string;
  'controls': string;
  'deleted': string;
  'editorSelect': string;
  'externalLinks': string;
  'link': string;
  'nextAiring': string;
  'overlayTitle': string;
  'poster': string;
  'posterContainer': string;
  'summary': string;
  'summaryTitle': string;
  'tags': string;
  'tagsList': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
