// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'info': string;
  'tags': string;
  'tagsList': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
