// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'sidebar': string;
  'sidebarContainer': string;
  'isCollapsed': string;
}
export const cssExports: CssExports;
export default cssExports;
