// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'countBadge': string;
  'error': string;
  'iconContainer': string;
  'info': string;
  'message': string;
  'success': string;
  'text': string;
  'warning': string;
}
export const cssExports: CssExports;
export default cssExports;
