// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'availNotMonitored': string;
  'continuing': string;
  'deleted': string;
  'ended': string;
  'missingMonitored': string;
  'missingUnmonitored': string;
  'queue': string;
}
export const cssExports: CssExports;
export default cssExports;
