// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'continuing': string;
  'date': string;
  'downloaded': string;
  'event': string;
  'eventWrapper': string;
  'genres': string;
  'missingMonitored': string;
  'missingUnmonitored': string;
  'movieTitle': string;
  'overlay': string;
  'queue': string;
  'releaseIcon': string;
  'statusIcon': string;
  'time': string;
  'underlay': string;
  'unmonitored': string;
}
export const cssExports: CssExports;
export default cssExports;
